### ISSUE TITLE
Donate button not working!

### ISSUE THREAD

**Issue by funnydoggie** [dvarrazzo/psycopg#19]
Dear Daniele,
Such a useful library, psycopg, thanks to you and the many other volunteers. Works like a charm and a huge time-saver...no issues with the code.
It's just that I'd like to donate US$12, but when I rolled over the "Donate" text, the link wasn't working.

Kind regards, and hope you have a lovely day!

**Comment by dvarrazzo** [comment]
Thank you for the idea. You should contact Federico, he's the one who installed that button. You can contact him as fog@initd.org.
